dts: fixes after tests
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>

diff --git a/meta-dts-distro/recipes-dts/dts/dts/cloud_list b/meta-dts-distro/recipes-dts/dts/dts/cloud_list
--- a/meta-dts-distro/recipes-dts/dts/dts/cloud_list
+++ b/meta-dts-distro/recipes-dts/dts/dts/cloud_list
@@ -49,5 +49,10 @@ HCL_REPORT_NAME=$(cat $TMP_LIST | grep -m1 $HW_UUID)
 
 # download HCL report
 tmpURL="https://cloud.3mdeb.com/public.php/webdav/$HCL_REPORT_NAME"
-curl -f -u "$USER_DETAILS" -H "$CLOUD_REQUEST" -X GET "$tmpURL" -o /$package
-error_check "Cannot download HCL report package."
+curl -f -u "$USER_DETAILS" -H "$CLOUD_REQUEST" -X GET "$tmpURL" -o /$HCL_REPORT_NAME
+if [ -f /$HCL_REPORT_NAME ]; then
+  echo "Report downloaded"
+else
+  echo "Report not found!"
+  exit 1
+fi
