dts: add bootsplash_migration()
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

diff --git a/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy b/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy
--- a/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy
+++ b/meta-dts-distro/recipes-dts/dts/dasharo-deploy/dasharo-deploy
@@ -260,6 +260,19 @@ smmstore_migration() {
     cbfstool "$BIOS_UPDATE_FILE" write -r SMMSTORE -f /tmp/smmstore.bin -u
 }
 
+bootsplash_migration() {
+    echo "Beginning BOOTSPLASH migration process..."
+    flashrom -p "$PROGRAMMER_BIOS" ${FLASH_CHIP_SELECT} -r /tmp/dasharo_dump.rom ${FLASHROM_ADD_OPT_READ} --fmap -i FMAP -i BOOTSPLASH >> $FLASHROM_LOG_FILE 2>> $ERR_LOG_FILE
+    cbfstool /tmp/dasharo_dump.rom extract -r BOOTSPLASH -n logo.bmp -f /tmp/logo.bmp >> $ERR_LOG_FILE 2>&1
+    if [ $? -ne 0 ]; then
+      echo "logo.bmp not found, nothing to migrate"
+      return 1
+    fi
+    echo "Migrate logo.bmp to BOOTSPLASH section."
+    cbfstool $BIOS_UPDATE_FILE remove -n logo.bmp -r BOOTSPLASH >> $ERR_LOG_FILE 2>&1
+    cbfstool $BIOS_UPDATE_FILE add -f /tmp/logo.bmp -r BOOTSPLASH -n logo.bmp -t raw -c lzma >> $ERR_LOG_FILE 2>&1
+}
+
 resign_binary() {
   if [ "$HAVE_VBOOT" -eq 0 ]; then
     download_keys
@@ -366,6 +379,10 @@ install() {
 
   if [ "$NEED_ROMHOLE_MIGRATION" = "true" ]; then
     romhole_migration
+  fi
+
+  if [ "$NEED_BOOTSPLASH_MIGRATION" = "true" ]; then
+    bootsplaash_migration
   fi
 
   if [ "$NEED_SMBIOS_MIGRATION" = "true" ]; then
@@ -501,6 +518,10 @@ update() {
 
   if [ "$NEED_SMMSTORE_MIGRATION" = "true" ]; then
     smmstore_migration
+  fi
+
+  if [ "$NEED_BOOTSPLASH_MIGRATION" = "true" ]; then
+    bootsplash_migration
   fi
 
   echo "Updating Dasharo firmware..."
