workflow: Fix build failure reported as success
Signed-off-by: Michał Iwanicki <michal.iwanicki@3mdeb.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,6 +11,8 @@ jobs:
   build:
     runs-on:
       labels: dts-builder
+    env:
+      FAILED_ATTEMPTS: 0
     steps:
       - name: Checkout meta-dts repo
         uses: actions/checkout@v4
@@ -31,17 +33,15 @@ jobs:
               break
             else
               echo "Build command failed on attempt $attempt"
+              echo "FAILED_ATTEMPTS=$attempt" >> $GITHUB_ENV
               if [ $attempt -lt 5 ]; then
                 sleep 5
+              else
+                exit 1
               fi
             fi
           done
-        continue-on-error: true
       - name: Report build command
+        if: always()
         run: |
-          if [ ${{ steps.build_image.outcome }} == 'failure' ]; then
-            echo "All build attempts failed."
-            exit 1
-          else
-            echo "At least one build attempt succeeded."
-          fi
+          echo "$FAILED_ATTEMPTS build attempts failed"
